// @vitest-environment jsdom
/**
 * The bundle smoke test for the portal build path (spec task 7.1, design §16.7).
 *
 * WHAT THIS TEST IS FOR
 * ---------------------
 * Design §16.7 draws a deliberate line: "Tests run against the source, not the
 * bundle, so a failure points at a line of TypeScript. One additional smoke test
 * parses each built bundle, boots it in jsdom against a fixture, and asserts it
 * defines no global beyond a single namespaced entry."
 *
 * This is that one test, and its job is narrow on purpose. It does not test what
 * a section does — nothing does yet, and when they do, those tests belong beside
 * the TypeScript. It tests the things that only exist AFTER esbuild has run and
 * that no source-level test can see:
 *
 *   1. Each committed artefact exists in `theme/assets/` and parses.
 *   2. Loading a bundle adds exactly ONE property to the global object.
 *   3. The core bundle's boot scan finds a `[data-portal-section]` root, runs
 *      the registered section, and isolates a section that throws.
 *   4. The asset name and the registered section name agree — the one place the
 *      `orderDetail.ts` to `athoor-portal-order-detail.js` transformation could
 *      silently diverge.
 *   5. No bundle carries a runtime dependency (Requirement 19.8) or a `zod`
 *      import dragged across the type-only boundary of `data/types.ts`.
 *
 * WHY IT READS FROM `theme/assets/` AND NEVER BUILDS
 * -------------------------------------------------
 * The committed artefacts are the deliverable (design §16.7, §25.5) — the bytes a
 * theme push sends to Shopify. A test that ran esbuild first would verify a build
 * output nobody ships and would pass while the committed files were stale. That
 * staleness is checked separately and mechanically by
 * `npm run build:portal:check`, which rebuilds and compares bytes; this test
 * checks the artefacts themselves. The two are complementary and neither
 * substitutes for the other.
 *
 * It also follows the precedent already in this directory: `_test-dirname.test.ts`
 * and `wishlistReconcile.dom.test.ts` read the real shipped
 * `theme/assets/athoor-loyalty.js` from disk rather than a copy.
 *
 * OWNERSHIP NOTE. Task 29.12 formally owns "the bundle smoke test" and will
 * extend this file with per-section fixtures as sections gain behaviour, and task
 * 29.11 owns the build-failing budget gate. This lands with 7.1 because a build
 * path with no test asserting its output is an unverified build path, and 7.1 is
 * the task that claims the output is correct.
 *
 * Validates: Requirements 20.1, 19.8, 18.3
 */
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { beforeEach, describe, expect, it } from "vitest";

/** `loyalty-service/src/theme` -> repository root. */
const REPO_ROOT = join(import.meta.dirname ?? new URL(".", import.meta.url).pathname, "..", "..", "..");
const ASSETS = join(REPO_ROOT, "theme", "assets");

/**
 * The ten section modules of design §16.2, paired with the asset each must
 * produce and the name each must register.
 *
 * Written out rather than derived from the directory. A derived list would be
 * generated by the same rule the build uses, so a mistake in that rule would
 * appear identically on both sides and the test would agree with the bug. This
 * table is an independent statement of the expected result.
 */
const SECTIONS = [
  { module: "activity.ts", asset: "athoor-portal-activity.js", name: "activity" },
  { module: "fragrance.ts", asset: "athoor-portal-fragrance.js", name: "fragrance" },
  { module: "orderDetail.ts", asset: "athoor-portal-order-detail.js", name: "order-detail" },
  { module: "orders.ts", asset: "athoor-portal-orders.js", name: "orders" },
  { module: "overview.ts", asset: "athoor-portal-overview.js", name: "overview" },
  { module: "profile.ts", asset: "athoor-portal-profile.js", name: "profile" },
  { module: "referrals.ts", asset: "athoor-portal-referrals.js", name: "referrals" },
  { module: "rewards.ts", asset: "athoor-portal-rewards.js", name: "rewards" },
  { module: "settings.ts", asset: "athoor-portal-settings.js", name: "settings" },
  { module: "wishlist.ts", asset: "athoor-portal-wishlist.js", name: "wishlist" },
] as const;

const CORE_ASSET = "athoor-portal-core.js";
const CSS_ASSET = "athoor-portal.css";

const readAsset = (name: string): string => readFileSync(join(ASSETS, name), "utf8");

/**
 * Runs a bundle the way a browser would and reports which global names it added.
 *
 * `new Function` rather than `eval`: it evaluates in the global scope of this
 * jsdom realm without inheriting this module's local bindings, which is closer to
 * a `<script>` tag and stops a bundle accidentally resolving a name from the test.
 */
function loadBundle(source: string): string[] {
  const before = new Set(Object.getOwnPropertyNames(globalThis));
  // eslint-disable-next-line no-new-func
  new Function(source).call(globalThis);
  return Object.getOwnPropertyNames(globalThis).filter((k) => !before.has(k));
}

/** Removes the namespace so each test starts from a browser's first page load. */
function resetRuntime(): void {
  delete (globalThis as { AthoorPortal?: unknown }).AthoorPortal;
}

/** A section root as task 19.4's Liquid will render it. */
function seedRoot(name: string): HTMLElement {
  const root = document.createElement("div");
  root.setAttribute("data-portal-section", name);
  document.body.appendChild(root);
  return root;
}

beforeEach(() => {
  document.body.innerHTML = "";
  resetRuntime();
});

describe("the committed artefacts", () => {
  it("includes the core bundle, one bundle per section, and one stylesheet", () => {
    const expected = [CORE_ASSET, ...SECTIONS.map((s) => s.asset), CSS_ASSET];
    const missing = expected.filter((asset) => !existsSync(join(ASSETS, asset)));

    // Design §16.7 and §25.5: a theme push must never require a build, which
    // holds only while these files are in the repository.
    expect(missing).toEqual([]);
  });

  it("keeps the stylesheet's provenance banner through minification", () => {
    // `theme/assets/` is editable in the Shopify admin. Without a banner naming
    // the source, an in-place edit there is silently reverted by the next build.
    const css = readAsset(CSS_ASSET);
    expect(css).toContain("theme-src/portal/styles");
    expect(css).toContain("npm run build:portal");
  });
});

describe("the core bundle", () => {
  it("defines exactly one global, and it is the namespaced entry", () => {
    const added = loadBundle(readAsset(CORE_ASSET));

    // The whole of design §16.7's global budget, asserted rather than trusted.
    expect(added).toEqual(["AthoorPortal"]);
  });

  it("exposes only the boot contract", () => {
    loadBundle(readAsset(CORE_ASSET));
    const runtime = (globalThis as { AthoorPortal?: Record<string, unknown> }).AthoorPortal;

    expect(runtime).toBeDefined();
    // Sorted so the assertion is order-independent, and exhaustive so a member
    // added without a task behind it fails here. Tasks 18.1–18.6 have now landed
    // and each added exactly one member; the four task-7.1 members are unchanged.
    expect(Object.keys(runtime ?? {}).sort()).toEqual([
      "announce",
      "boot",
      "cache",
      // 20.4 — the cart, in core so it is the only mutation boundary.
      "cart",
      "copy",
      "draft",
      "focus",
      "register",
      "registered",
      "request",
      "rows",
      "sessionRef",
      "sheet",
      "states",
      "version",
    ]);
  });

  it("still defines exactly ONE global after task 18's modules were added", () => {
    // The whole reason §16.7 bounds the bundles to "no global beyond a single
    // namespaced entry". Nine new members is nine chances to have leaked a
    // module-scoped helper onto `window`.
    const before = new Set(Object.getOwnPropertyNames(globalThis));
    loadBundle(readAsset(CORE_ASSET));
    const added = Object.getOwnPropertyNames(globalThis).filter((name) => !before.has(name));
    expect(added).toEqual(["AthoorPortal"]);
  });

  it("the transport is the portal's ONLY fetch boundary (Req 1.6)", () => {
    // Core owns the one `fetch`; no section bundle may contain another, because a
    // second call site is a second place the relative base path, the missing
    // credential and the idempotency header could each be got wrong.
    const core = readAsset(CORE_ASSET);
    expect(core, "core lost its fetch").toContain("fetch(");

    for (const section of SECTIONS) {
      const source = readAsset(section.asset);
      expect(source, `${section.asset} contains its own fetch`).not.toContain("fetch(");
      expect(source, `${section.asset} uses XMLHttpRequest`).not.toContain("XMLHttpRequest");
      expect(source, `${section.asset} uses sendBeacon`).not.toContain("sendBeacon");
      expect(source, `${section.asset} opens an EventSource`).not.toContain("EventSource");
    }
  });

  it("the cart is mutated from CORE only, and only via /cart/add.js (task 20.4)", () => {
    // Task 20 added the portal's second `fetch` boundary. It lives in core for the
    // same reason the API transport does: a second call site is a second place the
    // URL, the content type and the duplicate-submission guard can each be got
    // wrong — and this one has no idempotency key to fall back on.
    const core = readAsset(CORE_ASSET);
    expect(core, "core lost the cart client").toContain("/cart/add.js");

    for (const section of SECTIONS) {
      const source = readAsset(section.asset);
      expect(source, `${section.asset} writes the cart itself`).not.toContain("/cart/add.js");
      expect(source, `${section.asset} posts to some other cart route`).not.toMatch(/\/cart\/(add|change|update|clear)/);
    }

    // And no bundle reaches for any other Shopify mutation surface.
    for (const asset of [CORE_ASSET, ...SECTIONS.map((section) => section.asset)]) {
      const source = readAsset(asset);
      expect(source, `${asset} calls the Storefront API`).not.toContain("/api/graphql");
      expect(source, `${asset} calls the Admin API`).not.toContain("/admin/api");
    }
  });

  /**
   * The ONE bundle the approved design permits to touch client storage, and the one
   * key it may use.
   *
   * Task 23.2 grants the referrals section a single `localStorage` entry so a
   * customer who arrived on a `?ref=` link does not have to retype the code after
   * signing up. Narrowing the rule to that one key keeps the gate as strong as it
   * was everywhere else — and strong here too, since a second key, `sessionStorage`,
   * a cookie or `indexedDB` in this bundle still fails.
   */
  const STORAGE_EXCEPTION = { asset: "athoor-portal-referrals.js", key: "athoor_ref" } as const;

  it("no bundle writes to client storage, except the one key task 23.2 permits (Req 1.8)", () => {
    // The draft store and the request cache are both memory-only by design; this
    // is the assertion that keeps them that way after a future edit.
    for (const asset of [CORE_ASSET, ...SECTIONS.map((section) => section.asset)]) {
      const source = readAsset(asset);
      if (asset === STORAGE_EXCEPTION.asset) {
        // Permitted — but ONLY for the one named key. Every `localStorage` mention
        // in this bundle must be an access to it, so a second key cannot be added
        // without this assertion noticing.
        expect(source, `${asset} lost its ${STORAGE_EXCEPTION.key} capture`).toContain(
          STORAGE_EXCEPTION.key,
        );
        const keys = [...source.matchAll(/localStorage\.(getItem|setItem|removeItem)\(([^,)]+)/g)].map(
          (match) => match[2] ?? "",
        );
        expect(keys.length, `${asset} touches localStorage in an unrecognised way`).toBeGreaterThan(0);
        for (const key of keys) {
          // Minified to a single const, so the argument is an identifier rather than
          // the literal. Either spelling is fine; anything else is a second key.
          expect(
            key.includes(STORAGE_EXCEPTION.key) || /^[A-Za-z_$][\w$]*$/.test(key.trim()),
            `${asset} reads or writes a storage key other than ${STORAGE_EXCEPTION.key}: ${key}`,
          ).toBe(true);
        }
      } else {
        expect(source, `${asset} writes localStorage`).not.toContain("localStorage");
      }
      expect(source, `${asset} writes sessionStorage`).not.toContain("sessionStorage");
      expect(source, `${asset} writes document.cookie`).not.toContain("document.cookie");
      expect(source, `${asset} uses indexedDB`).not.toContain("indexedDB");
    }
  });

  it("the referrals bundle declares exactly ONE storage key (task 23.2)", () => {
    // The companion to the rule above, stated over the SOURCE rather than the
    // bundle, where the key is still a readable literal. Two string literals that
    // look like storage keys would mean the single-key rule had been broken in a way
    // minification could hide.
    const source = readAsset(STORAGE_EXCEPTION.asset);
    const literals = [...source.matchAll(/"([a-z][a-z0-9]*(?:[_-][a-z0-9]+)+)"/gi)]
      .map((match) => match[1] ?? "")
      .filter((value) => value === STORAGE_EXCEPTION.key);
    expect(new Set(literals).size, "more than one storage key literal").toBe(1);
  });

  it("the core bundle never names the Render origin (Req 1.7)", () => {
    const core = readAsset(CORE_ASSET);
    expect(core).not.toContain("onrender.com");
    expect(core).not.toMatch(/https?:\/\/[a-z0-9-]+\.onrender/i);
    // The App Proxy base is relative, and that is the whole authentication story.
    expect(core).toContain("/apps/loyalty/v1");
  });

  it("no bundle carries a secret-shaped literal", () => {
    for (const asset of [CORE_ASSET, ...SECTIONS.map((section) => section.asset)]) {
      const source = readAsset(asset);
      expect(source, `${asset} carries a Shopify token`).not.toMatch(/shp(at|ua|ss|ca)_[A-Za-z0-9]/);
      expect(source, `${asset} carries a connection string`).not.toMatch(/postgres(ql)?:\/\//i);
      expect(source, `${asset} carries a private key`).not.toContain("BEGIN PRIVATE KEY");
    }
  });

  it("is idempotent, so a doubly-included tag cannot discard registrations", () => {
    const core = readAsset(CORE_ASSET);
    loadBundle(core);
    const first = (globalThis as { AthoorPortal?: unknown }).AthoorPortal;

    loadBundle(core);

    expect((globalThis as { AthoorPortal?: unknown }).AthoorPortal).toBe(first);
  });
});

describe("each section bundle", () => {
  it.each(SECTIONS)("$asset adds no global of its own", ({ asset }) => {
    loadBundle(readAsset(CORE_ASSET));

    const added = loadBundle(readAsset(asset));

    // `AthoorPortal` already exists by now, so a section bundle must add nothing
    // at all. This is what makes per-section bundling safe: ten more scripts on
    // a page and still one name on `window`.
    expect(added).toEqual([]);
  });

  it.each(SECTIONS)("$asset registers exactly '$name'", ({ asset, name }) => {
    loadBundle(readAsset(CORE_ASSET));

    loadBundle(readAsset(asset));
    const runtime = (globalThis as { AthoorPortal?: { registered(): string[] } }).AthoorPortal;

    // Pins the asset-name/section-name agreement — the one place the
    // `orderDetail.ts` -> `order-detail` transformation could drift unnoticed,
    // because a mismatch produces a section that simply never boots.
    expect(runtime?.registered()).toEqual([name]);
  });

  it.each(SECTIONS)("$asset boots the matching root and marks it", ({ asset, name }) => {
    const root = seedRoot(name);
    loadBundle(readAsset(CORE_ASSET));

    loadBundle(readAsset(asset));

    expect(root.getAttribute("data-portal-booted")).toBe("true");
  });
});

describe("boot behaviour", () => {
  it("leaves a root alone when its bundle was not loaded", () => {
    // The point of per-section bundling: a page carries roots whose code it did
    // not download, and those roots must keep their server-rendered content.
    const root = seedRoot("orders");

    loadBundle(readAsset(CORE_ASSET));

    expect(root.hasAttribute("data-portal-booted")).toBe(false);
  });

  it("isolates a section that throws, and still boots the next one", () => {
    // Requirement 15.1 — per-section failure isolation. Asserted against the
    // built core bundle, using a deliberately failing registration, because the
    // isolation is what stops one broken section taking the page with it.
    const broken = seedRoot("broken");
    const working = seedRoot("orders");
    loadBundle(readAsset(CORE_ASSET));
    const runtime = (globalThis as {
      AthoorPortal?: {
        register(n: string, b: (r: HTMLElement) => void): void;
        boot(): void;
      };
    }).AthoorPortal;

    runtime?.register("broken", () => {
      throw new Error("section boot failure");
    });
    let workingBooted = false;
    runtime?.register("orders", () => {
      workingBooted = true;
    });
    expect(() => runtime?.boot()).not.toThrow();

    expect(broken.getAttribute("data-portal-booted")).toBe("failed");
    expect(workingBooted).toBe(true);
  });

  it("does not re-run a section that already booted", () => {
    // A repeated `boot()` is normal: core scans on load and every section bundle
    // calls it again as it arrives. Re-invoking a booted section would duplicate
    // its listeners and its requests.
    const root = seedRoot("orders");
    loadBundle(readAsset(CORE_ASSET));
    const runtime = (globalThis as {
      AthoorPortal?: { register(n: string, b: () => void): void; boot(): void };
    }).AthoorPortal;

    let calls = 0;
    runtime?.register("orders", () => {
      calls += 1;
    });
    runtime?.boot();
    runtime?.boot();
    runtime?.boot();

    expect(calls).toBe(1);
    expect(root.getAttribute("data-portal-booted")).toBe("true");
  });

  it("ignores a root whose section name is empty", () => {
    const root = document.createElement("div");
    root.setAttribute("data-portal-section", "");
    document.body.appendChild(root);

    loadBundle(readAsset(CORE_ASSET));

    expect(root.hasAttribute("data-portal-booted")).toBe(false);
  });
});

describe("no runtime dependency reaches a theme asset", () => {
  const allJs = [CORE_ASSET, ...SECTIONS.map((s) => s.asset)];

  it.each(allJs)("%s contains no bundled node_modules code", (asset) => {
    const source = readAsset(asset);

    // Requirement 19.8 and design §16.7: esbuild adds no polyfill and no helper
    // library, and `data/types.ts` re-exports the service contract as TYPES ONLY
    // so esbuild never resolves the path into the service's module graph. `zod`
    // is the specific hazard: it sits one import away from the canonical
    // contract, and a stray value import would pull it into a theme asset.
    expect(source).not.toContain("zod");
    expect(source).not.toContain("node_modules");
    expect(source).not.toContain("require(");
    expect(source).not.toContain("process.env");
  });

  it.each(allJs)("%s is a single strict-mode IIFE with no module syntax", (asset) => {
    const source = readAsset(asset);

    // `format: "iife"` is what keeps every module-scoped name private, which is
    // the mechanism behind the one-global guarantee above. A stray `export` or
    // `import` would also fail outright in a `<script>` tag.
    expect(source.startsWith('"use strict";(()=>{')).toBe(true);
    expect(source).not.toMatch(/^\s*(import|export)\s/m);
  });

  it.each(allJs)("%s ships no source map reference", (asset) => {
    // A `.map` in `theme/assets/` would be pushed to Shopify and served
    // publicly, and would add an unreviewed file to the scoped-push list of
    // design §25.5.
    expect(readAsset(asset)).not.toContain("sourceMappingURL");
  });
});
